version: "3.8"
services:
  task-manager:
    build: .
    ports:
      -"2300:2300"
    environment:
      NODE_ENV: production
      DB_USER: admin
      DB_PORT: 5432
      DB_DATABASE: taskdb
      DB_PASS: 90700675
      DB_HOST: postgres
      ACCESS_TOKEN_SECRET: KLFJPMC2I4U987549RYGCB3H42I9U89Y7394
      REFRESH_TOKEN_SECRET: kbfioiejiuryyuwuedbdsjnk
      BACKEND_URL: http://localhost:2300
    depends_on:
      - db
  db:
    image: postgres
    ports:
      -"5435:5432",
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 90700675
      POSTGRES_DB: taskdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


